/*You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
*/

#include <iostream>
using namespace std;
class Solution
{
public:
    char findTheDifference(string s, string t)
    {

        int a = 0;
        for (int i = 0; i < s.size(); i++)
        {
            a ^= s[i];
        }
        for (int i = 0; i < t.size(); i++)
        {
            a ^= t[i];
        }
        return a;
    }
};
